Feature/ab/support diff units
svenwiegand/time-duration-picker pull request #4
Opened 2016-11-19 15:38 UTC by anishbajpai014

Finished adding alternate units to widget.
I've tried not to make unnecessary changes to the code base.

2016-11-20 14:47 UTC, svenwiegand requested changes
Thanks for implementing this! This looks good from a technical point of view. Just have two concerns:
1. Would prefer usage of the constants you've defined instead of using "magic numbers".
2. Most of the highlighted changes formatting changes. Maybe due to automatic formatting? Could you roll them back, so that only changes in content remain?

Thanks in advance...

2016-11-20 14:47 UTC, svenwiegand commented on time-duration-picker/src/main/java/mobi/upod/timedurationpicker/TimeDurationPicker.java
> +    private int timeUnits = 0;
Would prefer `HH_MM_SS` default assignment instead of "magic number".

2016-11-20 14:47 UTC, svenwiegand commented on time-duration-picker/src/main/java/mobi/upod/timedurationpicker/TimeDurationPicker.java
> +         *
Reformatting due to automatic code style (here an in subsequent methodes)?

2016-11-20 14:47 UTC, svenwiegand commented on time-duration-picker/src/main/java/mobi/upod/timedurationpicker/TimeDurationPicker.java
> +        displayViews = new TextView[]{hoursView, minutesView, secondsView};
Automatic formatting?

2016-11-20 14:47 UTC, svenwiegand commented on time-duration-picker/src/main/java/mobi/upod/timedurationpicker/TimeDurationPicker.java
> +        unitLabelViews = new TextView[]{hoursLabel, minutesLabel, secondsLabel};
Automatic formatting?

2016-11-20 14:47 UTC, svenwiegand commented on time-duration-picker/src/main/java/mobi/upod/timedurationpicker/TimeDurationPicker.java
> +                (Button) findViewById(R.id.numPad1), (Button) findViewById(
Line breaks due to automatic formatting?

2016-11-20 14:47 UTC, svenwiegand commented on time-duration-picker/src/main/java/mobi/upod/timedurationpicker/TimeDurationPicker.java
> +        hoursView.setVisibility(timeUnits == 0 || timeUnits == 1 ? View.VISIBLE : View.GONE);
Would prefer usage of constants defined above instead of "magic number" 0 to 2.

2016-11-20 15:01 UTC, anishbajpai014 commented on time-duration-picker/src/main/java/mobi/upod/timedurationpicker/TimeDurationPicker.java
> +         *
I find this funny since I commented that I tried to not make unnecessary changes. Will roll these back.

2016-11-20 16:37 UTC, anishbajpai014 commented
Have committed requested changes. Please review and notify me of any other required changes.

2016-11-24 14:04 UTC, merged

2016-11-24 14:05 UTC, svenwiegand commented
Looks good now. Thanks for your contribution. Will publish a new version soon.

2016-11-25 15:15 UTC, anishbajpai014 commented
Sounds great! Glad to have helped make a great library better.